---
# This playbook deploys a simple standalone Tomcat 7 server.

- hosts: tomcat-servers
  remote_user: root
  become: yes
  become_method: sudo
  vars:
    http_port: 80
    max_clients: 200
    mariadb_port: 3306
  tasks:
  - name: ensure mariadb is at the latest version
    yum:
      name: mariadb-server
      state: latest
  - name: ensure mariadb is running
    service:
      name: mariadb
      state: started
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
  - name: ensure apache is running
    service:
      name: httpd
      state: started
  handlers:
  - name: restart mariadb
    service:
      name: mariadb
      state: restarted
  - name: restart apache
    service:
      name: httpd
      state: restarted
  roles:
    - selinux
    - tomcat
    - apache
